// <auto-generated />
using System;
using CloudFileServer.Persistent;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudFileServer.Persistent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306062144_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloudFileServer.Domain.Models.Node", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<short>("NodeTypeId")
                        .HasColumnType("smallint");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NodeTypeId");

                    b.HasIndex("ParentId");

                    b.ToTable("Nodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Root",
                            NodeTypeId = (short)1,
                            UpdatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Documents",
                            NodeTypeId = (short)1,
                            ParentId = 1L,
                            UpdatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Images",
                            NodeTypeId = (short)1,
                            ParentId = 1L,
                            UpdatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Personal",
                            NodeTypeId = (short)1,
                            ParentId = 1L,
                            UpdatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Annual Report",
                            NodeTypeId = (short)2,
                            ParentId = 2L,
                            SizeBytes = 153600L,
                            StoragePath = "docs/annual-report.docx",
                            UpdatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Meeting Notes",
                            NodeTypeId = (short)4,
                            ParentId = 2L,
                            SizeBytes = 2048L,
                            StoragePath = "docs/meeting-notes.txt",
                            UpdatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Sunset",
                            NodeTypeId = (short)3,
                            ParentId = 3L,
                            SizeBytes = 512000L,
                            StoragePath = "images/sunset.jpg",
                            UpdatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Profile",
                            NodeTypeId = (short)3,
                            ParentId = 3L,
                            SizeBytes = 204800L,
                            StoragePath = "images/profile.jpg",
                            UpdatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Diary",
                            NodeTypeId = (short)2,
                            ParentId = 4L,
                            SizeBytes = 81920L,
                            StoragePath = "personal/diary.docx",
                            UpdatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeImageMeta", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<int>("HeightPx")
                        .HasColumnType("int");

                    b.Property<int>("WidthPx")
                        .HasColumnType("int");

                    b.HasKey("NodeId");

                    b.ToTable("NodeImageMeta", (string)null);
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeTag", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("NodeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("NodeTags", (string)null);

                    b.HasData(
                        new
                        {
                            NodeId = 5L,
                            TagId = 1
                        },
                        new
                        {
                            NodeId = 5L,
                            TagId = 2
                        },
                        new
                        {
                            NodeId = 6L,
                            TagId = 2
                        },
                        new
                        {
                            NodeId = 8L,
                            TagId = 3
                        },
                        new
                        {
                            NodeId = 9L,
                            TagId = 3
                        });
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeTextMeta", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Encoding")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NodeId");

                    b.ToTable("NodeTextMeta", (string)null);
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<short>("Code")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("NodeTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = (short)0,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsLeaf = false
                        },
                        new
                        {
                            Id = (short)2,
                            Code = (short)1,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsLeaf = true
                        },
                        new
                        {
                            Id = (short)3,
                            Code = (short)2,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsLeaf = true
                        },
                        new
                        {
                            Id = (short)4,
                            Code = (short)3,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsLeaf = true
                        });
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeWordMeta", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.HasKey("NodeId");

                    b.ToTable("NodeWordMeta", (string)null);

                    b.HasData(
                        new
                        {
                            NodeId = 5L,
                            PageCount = 12
                        },
                        new
                        {
                            NodeId = 9L,
                            PageCount = 5
                        });
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#F44336",
                            Name = "Urgent"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#2196F3",
                            Name = "Work"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#4CAF50",
                            Name = "Personal"
                        });
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.Node", b =>
                {
                    b.HasOne("CloudFileServer.Domain.Models.NodeType", null)
                        .WithMany()
                        .HasForeignKey("NodeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CloudFileServer.Domain.Models.Node", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeImageMeta", b =>
                {
                    b.HasOne("CloudFileServer.Domain.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("CloudFileServer.Domain.Models.NodeImageMeta", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeTag", b =>
                {
                    b.HasOne("CloudFileServer.Domain.Models.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudFileServer.Domain.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeTextMeta", b =>
                {
                    b.HasOne("CloudFileServer.Domain.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("CloudFileServer.Domain.Models.NodeTextMeta", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeWordMeta", b =>
                {
                    b.HasOne("CloudFileServer.Domain.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("CloudFileServer.Domain.Models.NodeWordMeta", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
