// <auto-generated />
using System;
using CloudFileServer.Persistent;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudFileServer.Persistent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloudFileServer.Domain.Models.Node", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<short>("NodeTypeId")
                        .HasColumnType("smallint");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NodeTypeId");

                    b.HasIndex("ParentId");

                    b.ToTable("Nodes", (string)null);
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeImageMeta", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<int>("HeightPx")
                        .HasColumnType("int");

                    b.Property<int>("WidthPx")
                        .HasColumnType("int");

                    b.HasKey("NodeId");

                    b.ToTable("NodeImageMeta", (string)null);
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeTag", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("NodeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("NodeTags", (string)null);
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeTextMeta", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Encoding")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NodeId");

                    b.ToTable("NodeTextMeta", (string)null);
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<short>("Code")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("NodeTypes", (string)null);
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeWordMeta", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.HasKey("NodeId");

                    b.ToTable("NodeWordMeta", (string)null);
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Color = "#FF9800",
                            Name = "Review"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#9E9E9E",
                            Name = "Archive"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#9C27B0",
                            Name = "Draft"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#00BCD4",
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#8BC34A",
                            Name = "Shared"
                        });
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.Node", b =>
                {
                    b.HasOne("CloudFileServer.Domain.Models.NodeType", null)
                        .WithMany()
                        .HasForeignKey("NodeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CloudFileServer.Domain.Models.Node", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeImageMeta", b =>
                {
                    b.HasOne("CloudFileServer.Domain.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("CloudFileServer.Domain.Models.NodeImageMeta", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeTag", b =>
                {
                    b.HasOne("CloudFileServer.Domain.Models.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudFileServer.Domain.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeTextMeta", b =>
                {
                    b.HasOne("CloudFileServer.Domain.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("CloudFileServer.Domain.Models.NodeTextMeta", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudFileServer.Domain.Models.NodeWordMeta", b =>
                {
                    b.HasOne("CloudFileServer.Domain.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("CloudFileServer.Domain.Models.NodeWordMeta", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
